[config]
skip_core_tasks = true
[tasks.all]
run_task = [
	{name = ["other", "popup"]}
]
[tasks.test]
run_task = [
	{name = ["test_other", "test_popup", "e2e_popup"]}
]
[tasks.other]
run_task = [
	{name = ["clean_other", "build_other", "copy_other"]}
]
[tasks.popup]
run_task = [
	{name = ["clean_popup", "build_popup", "copy_popup"]}
]
[tasks.clean_other]
category = "other_file"
script = [
'''
rm -rf dist/js dist/manifest.json dist/options.html dist/icon.png
'''
]
[tasks.build_other]
category = "other_file"
script = [
'''
cd other
yarn build
'''
]
[tasks.copy_other]
category = "other_file"
script = [
'''
cd other/dist && \
cp -r js ../../dist/ && \
cp icon.png ../../dist/icon.png && \
cp manifest.json ../../dist/manifest.json && \
cp options.html ../../dist/options.html
'''
]
[tasks.test_other]
category = "other_file"
script = [
'''
cd other && \
yarn test
'''
]
[tasks.clean_popup]
category = "popup_file"
script = [
'''
rm -rf dist/static dist/popup.html
'''
]
[tasks.build_popup]
category = "popup_file"
script = [
'''
cd popup && \
yarn build
'''
]
[tasks.copy_popup]
category = "popup_file"
script = [
'''
cd popup/build && \
cp index.html ../../dist/popup.html && \
cp -r static ../../dist/
'''
]
[tasks.test_popup]
category = "popup_file"
script = [
'''
cd popup && \
yarn test
'''
]
[tasks.e2e_popup]
category = "popup_file"
script = [
'''
cd popup && \
yarn e2e:headfull
'''
]